---
version: '3'
services:

  ## PostgreSQL database
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: toyota
    ports:
      - "5432:5432"

  ## Eureka Server
  discovery-server:
    image: zormanfayci/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"

  ## Api-gateway
  api-gateway:
    image: zormanfayci/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server
      - token-service

  ## Token-Service Docker Compose Config
  token-service:
    container_name: token-service
    image: zormanfayci/token-service:latest
    pull_policy: always
    ports:
      - "8083:8083"
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      -SPRING_DATASOURCE_USERNAME: postgres
      -SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      #- SPRING_PROFILES_ACTIVE=docker
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/toyota
    depends_on:
      - discovery-server

  ## admin-terminal-service Docker Compose Config
  admin-terminal-service:
    container_name: admin-terminal-service
    image: zormanfayci/admin-terminal-service:latest
    pull_policy: always
    ports:
      - "8081:8081"
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      -SPRING_DATASOURCE_USERNAME: postgres
      -SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
     # - SPRING_PROFILES_ACTIVE=docker
     # - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/toyota
    depends_on:
      - discovery-server
      - api-gateway

    ## operator-teamleader-service
  operator-teamleader-service:
    container_name: operator-teamleader-service
    image: zormanfayci/operator-teamleader-service:latest
    pull_policy: always
    ports:
      - "8082:8082"
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      -SPRING_DATASOURCE_USERNAME: postgres
      -SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      # - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/toyota
    depends_on:
      - discovery-server
      - api-gateway